generator/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.law_select, name='law_select'),
    path('parameters/<law_name>/', views.param_select, name='param_select'),
    path('parameters/<law_name>/<params>/', views.simu, name='simu'),
    path('download', views.download, name='download')
]

sparsegenerator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator.urls')),
]

generator/models.py
from django.db import models

generator/forms.py
from django import forms


LAWS = [
    ('gaussian', 'Gaussian'),
    ('laplace', 'Laplace'),
    ('gamma', 'Gamma'),
    ('alpha_stable', 'Alpha Stable')
]

class LawForm(forms.Form):
    law_name = forms.ChoiceField(choices=LAWS, widget=forms.RadioSelect(), initial="gaussian")

class Gaussian(forms.Form):
    variance = forms.FloatField(min_value=0, initial=1)

class Alpha(forms.Form):
    alpha = forms.FloatField(min_value=0, max_value=2, initial=1)

class Laplace(forms.Form):
    scale = forms.FloatField(min_value=0, initial=1)

class Gamma(forms.Form):
    shape = forms.FloatField(min_value=0, initial=1)
    scale = forms.FloatField(min_value=0, initial=1)

class SimulationForm(forms.Form):
    p = forms.CharField(label="P",initial="1, 0")
    q = forms.CharField(label="Q", initial="1")
    T = forms.FloatField(min_value=0, label="Simulation interval T", initial=1)
    h = forms.FloatField(min_value=0, label="Step size h", initial=0.01)
    numsim = forms.IntegerField(min_value=1, max_value=10000, label="Number of simulations")

generator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import LawForm, Gaussian, Laplace, Alpha, Gamma, SimulationForm
from .libs import white_noise, loperator, lspline
import matplotlib.pyplot as plt
import numpy as np
import os


LAWS = {
    'gaussian' :  'Gaussian',
    'laplace': 'Laplace',
    'gamma': 'Gamma',
    'alpha_stable': 'Alpha Stable'
}

def law_select(request):
    if request.method == "POST":
        form = LawForm(request.POST)
        if form.is_valid():
            return redirect('param_select', law_name=form.cleaned_data['law_name'])
    else:
        form = LawForm()
    return render(request, 'generator/lawinput.html', {'form' : form})

def param_select(request, law_name):
    laws = {'gaussian': Gaussian,'alpha_stable': Alpha,'laplace': Laplace,'gamma' : Gamma}
    if request.method == "POST":
        form = laws[law_name](request.POST)
        if form.is_valid():
            params = list(form.cleaned_data.values())
            return redirect('simu', law_name=law_name, params=params)
    else:
        form = laws[law_name]
    return render(request, 'generator/paraminput.html', {'law':LAWS[law_name], 'form':form})

def simu(request, law_name, params):
    if request.method == "POST":
        form = SimulationForm(request.POST)
        if form.is_valid():
            params = params[1:-1].split(',')
            w = white_noise.white_noise(law_name, list(map(float, params)))
            P = list(map(float, form.cleaned_data['p'].split(',')))
            Q = list(map(float, form.cleaned_data['q'].split(',')))

            L = loperator.Operator(P, Q)
            s = lspline.L_spline(L, w)




            T = float(form.cleaned_data['T'])
            h = float(form.cleaned_data['h'])

            s.set_lambda(np.ceil(1/h)*5)

            DATA = []
            numsim = int(form.cleaned_data['numsim'])

            for _ in range(numsim):
                s.sample(T)
                grid, dt = s.get_grid_samples(T, h, show=False)
                DATA.append(dt)
            dir = os.path.join(os.getcwd(), "generator", "static")
            np.savetxt(os.path.join(dir , "data.csv"), DATA)


            plt.style.use('seaborn-poster')

            plt.step(grid, dt, where='post', lw = 1.5)
            plt.savefig(os.path.join(dir, "fig.png"), format='png')
            plt.close()

            return redirect('download')

    else:
        form = SimulationForm()
    print(law_name, params)
    return render(request, 'generator/simulationinput.html', {'form':form})

def download(request):
    return render(request, 'generator/download.html', {"figure": os.path.join(os.getcwd(), "generator", "static") + "fig.png", "data": os.path.join(os.getcwd(), "generator", "static") + "data.csv"})

generator/templates/generator/download.html
{% extends 'generator/index.html' %}
{% load static %}


{% block content %}
<div class=row>

  <div class="col-sm-6">
    <img class="plot" src="{% static 'fig.png' %}"/>
  </div>

  <div class="col-sm-3">

    <a class="download-button" href= "{% static 'data.csv' %}">DOWNLOAD</a>

  </div>

</div>
{% endblock %}

generator/templates/generator/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href = "{% static 'style.css' %}" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="https://fonts.googleapis.com/css?family=Arvo|Merriweather&display=swap" rel="stylesheet">


  <!-- Loading mathjax macro -->
  <!-- Load mathjax -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_HTML"></script>
      <!-- MathJax configuration -->
      <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
          tex2jax: {
              inlineMath: [ ['$','$'], ["\\(","\\)"] ],
              displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
              processEscapes: true,
              processEnvironments: true
          },
          // Center justify equations in code and markdown cells. Elsewhere
          // we use CSS to left justify single line equations in code cells.
          displayAlign: 'center',
          "HTML-CSS": {
              styles: {'.MathJax_Display': {"margin": 0}},
              linebreaks: { automatic: true }
          }
      });
      </script>
      <!-- End of mathjax configuration -->
</head>

<body>
  <span class="title">Sparse<br/>Stochastic<br/>Process<br/>Generator</span>
  <div class='banner'></div>
  <div class='block'>
  {% block content %}
  {% endblock %}
  </div>
</body>

</html>

generator/templates/generator/lawinput.html
{% extends 'generator/index.html' %}

{% block content %}
<h4>Select white Levy noise statistics :</h4>
<form method="POST" >
    {% csrf_token %}


        <div class="row align-middle">

                <div class="col-sm-4">
                <p>
                Choose the infinitely divisible law defining the white noise $w$ . The distribution will correspond to the law of 
                $$
                \langle \mathrm{rect}_{[0, 1]}, w \rangle
                $$
                </p>
                </div>

                <div class="col-sm-3">

                <p class="">
                <ul>
                    <li><label for="id_law_name_0"><input type="radio" name="law_name" checked value="gaussian" required    id="id_law_name_0" />  Gaussian</label>

                    </li>
                    <li><label for="id_law_name_1"><input type="radio" name="law_name" value="laplace" required id="id_law_name_1" />  Laplace</label>

                    </li>
                    <li><label for="id_law_name_2"><input type="radio" name="law_name" value="gamma" required id="id_law_name_2" />  Gamma</label>

                    </li>
                    <li><label for="id_law_name_3"><input type="radio" name="law_name" value="alpha_stable" required id="id_law_name_3" />  Alpha Stable</label>

                    </li>
                </ul>
                </p>


                </div>

                <div class="col-sm-2">
                  <div>
                    <button type="submit" class="button-class">NEXT</button>
                  </div>

       </div>



</form>



{% endblock %}

generator/templates/generator/paraminput.html
{% extends 'generator/index.html' %}

{% block content %}
<h4>Select parameters of the white noise : </h4>
<form method="POST" class="post-form">
      {% csrf_token %}

      <div class="row align-middle">
        <div class="col-sm-4">
        Fix the parameters of the <code>{{ law }}</code> distribution.
        </div>

        <div class="col-sm-3">

          {{ form.as_p }}

        </div>

        <div class="col-sm-2">
          <div>
            <button type="submit" class="button-class">NEXT</button>
          </div>
         </div>
        </div>





</form>
{% endblock %}

generator/templates/generator/simulationinput.html
{% extends 'generator/index.html' %}

{% block content %}
<h4>Simulation Details: </h4>
<form method="POST" class="post-form">
      {% csrf_token %}

      <div class="row align-middle">
        <div class="col-sm-5">
          <p>Input the rational operator of the form
  $$
  P(\mathrm{D})Q(\mathrm{D})^{-1}
  $$
  The polynomials $P$ and $Q$ are defined through the list of their coefficients :</p>
  <ul>
  <li>$P(\mathrm{D}) = p_0 \mathrm{D}^n + p_1 \mathrm{D}^{n-1} + ... + p_n$ is represented as <br/>
    <center><code>P = p_0, ..., p_n </code> </center></li>
  <li>$Q(\mathrm{D}) = q_0 \mathrm{D}^m + q_1 \mathrm{D}^{m-1} + ... + q_m$ is represented as <br/>
     <center><code>Q = q_0, ..., q_m</code></center></li>
  </ul>
  <p>Define the operators by providing comma separated lists of the coefficients of  <code>P</code> and <code>Q</code>.
    </div>

        <div class="col-sm-3">

          <table>
      <tr>
        <td><label for="id_p">Coefficients of P : </label></td>
        <td><input type="text" name="p" required id="id_p" value="1, 0"/></td>
      </tr>
      <tr>
        <td><label for="id_q">Coefficients of Q : </label></td>
        <td><input type="text" name="q" required id="id_q" value="1"/></td>
      </tr>
      </table>
      </div>
      </div>
      <br/>
      <div class="row align-middle">
        <div class="col-sm-5">
          Select the simulation interval <code>[0, T]</code> <br/>
          The step <code>h</code> of the grid on the interval. <br/>
          And the number of independent trajectories you wish to generate.
        </div>

        <div class="col-sm-3">
          <table>

      <tr>
        <td><label for="id_T">Simulation interval T:</label></td>
        <td><input type="number" name="T" min="0" step="any" required id="id_T" value="1"/></td>
      </tr>
      <tr>
        <td><label for="id_h">Step size h:</label></td>
        <td><input type="number" name="h" min="0" step="any" required id="id_h" value="0.001"/></td>
      </tr>
      <tr>
        <td><label for="id_numsim">Number of simulations:</label></td>
        <td><input type="number" name="numsim" min="1" max="10000" required id="id_numsim" value="1"/></td>
      </tr>
          </table>

        </div>

        <div class="col-sm-2">
          <div class="button">
            <button type="submit" class="button-class-gen">GENERATE</button>
          </div>
          </div>
        </div>



</form>
{% endblock %}